#!/usr/bin/with-contenv bash
. /opt/conda/etc/profile.d/conda.sh

set -e

conda activate base

WORK_PATH="${WORKDIR:-/work}"

export CONDA_ENV_PATH="${WORK_PATH}/${CONDA_FILE:-environment.yml}"
export PIP_REQUIREMENTS_PATH="${WORK_PATH}/${PIP_REQUIREMENTS:-requirements.txt}"

if [ -f "${CONDA_ENV_PATH}" ]; then
  mamba env create -f "${CONDA_ENV_PATH}"
  export ENV_NAME=`cat "${CONDA_ENV_PATH}" | grep 'name: ' | sed 's/name: \(.*\)/\1/'`
  echo "${ENV_NAME}" >> /tmp/CONDA_ENV
  conda activate "${ENV_NAME}"
fi

if [ -f "${PIP_REQUIREMENTS_PATH}" ]; then
  pip install -r "${PIP_REQUIREMENTS_PATH}"
fi
