on:
  push:
    branches:
      - development
    tags:
      - 'v*'

jobs:
  build_base:
    name: Build base
    runs-on: [self-hosted, linux]

    env:
      container-name: base

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build ${{ env.container-name }}
        uses: TNTLFreiburg/gh-build-container@main
        with:
          image-name: ${{ env.container-name }}
