on:
  push:
    branches:
      - development
    tags:
      - 'v*'

jobs:
  build_base:
    name: Build base
    runs-on: [self-hosted, linux]

    env:
      container-name: base

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: cr.nail.science/ml-containers/${{ env.container-name }}
          tag-semver: |
            {{major}}
            {{major}}.{{minor}}
            {{major}}.{{minor}}.{{patch}}

      - name: Download buildctl
        run: curl -sL https://github.com/moby/buildkit/releases/download/v0.9.0/buildkit-v0.9.0.linux-amd64.tar.gz | tar xvzf - -C /usr/local bin/buildctl

      - name: Login to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: cr.nail.science
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_TOKEN }}

      - name: Build and push
        working-directory: base/
        run: |
          buildctl --addr unix:///mnt/buildkit/buildkitd.sock \
            build \
            --frontend dockerfile.v0 \
            --local context=. \
            --local dockerfile=. \
            --output type=image,\"name=${{ steps.meta.outputs.tags }}\",push=true \
            --export-cache type=inline \
            --import-cache type=registry,ref=cr.nail.science/ml-containers/${{ env.container-name }}
